"""Diagnose teacher-forced BC error and closed-loop error accumulation.

This entry point is intentionally separate from the official challenge code.
It uses the frozen trajectory selection, first replays expert actions in the
current simulator, and then compares BC predictions on expert observations
and on observations generated by the policy itself.
"""

import argparse
import copy
import csv
import gc
import os
from datetime import datetime
from pathlib import Path
import sys

import numpy as np
import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
DEXGRASP_ROOT = REPO_ROOT / "dexgrasp"
for import_root in (str(REPO_ROOT), str(DEXGRASP_ROOT)):
    if import_root not in sys.path:
        sys.path.insert(0, import_root)

from custom_tools import evaluate_bc as evaluation_support  # noqa: E402
from custom_tools.train_residual_ppo import (  # noqa: E402
    DEFAULT_BC_CHECKPOINT, build_task, indexed_trajectory_data)


STAGES = (
    ("approach", 0, 30),
    ("pregrasp", 30, 41),
    ("closure", 41, 55),
    ("lift", 55, 69),
)
ACTION_GROUPS = (
    ("all", 0, 28),
    ("wrist_position", 0, 3),
    ("wrist_orientation", 3, 6),
    ("fingers", 6, 28),
)


def process_observation(observation, pro_dim, torch):
    """Apply the same feature mask used by the official BC evaluator."""
    fingertip_velocity = torch.arange(
        84, 149, device=observation.device).reshape(5, 13)[:, -6:].reshape(-1)
    removed = [
        torch.arange(56, 84, device=observation.device),
        torch.arange(149, 179, device=observation.device),
        fingertip_velocity,
    ]
    if pro_dim in (100, 128):
        removed.append(torch.arange(216, 222, device=observation.device))
    if pro_dim == 100:
        removed.append(torch.arange(28, 56, device=observation.device))
    if pro_dim not in (100, 128, 134):
        raise ValueError("Unsupported proprioception dimension: {}".format(pro_dim))
    mask = torch.ones(2582, dtype=torch.bool, device=observation.device)
    mask[torch.cat(removed)] = False
    return observation[..., mask]


def parse_cli():
    parser = argparse.ArgumentParser(
        description="BC teacher-forcing versus closed-loop diagnostic.")
    parser.add_argument(
        "--trajectory-selection", default=str(
            REPO_ROOT / "custom_tools/configs/"
            "residual_full16_trajectory_selection.yaml"))
    parser.add_argument("--trajectory-root", default="")
    parser.add_argument("--bc-checkpoint", default=str(DEFAULT_BC_CHECKPOINT))
    parser.add_argument("--bc-config", default=str(
        REPO_ROOT / "custom_tools/configs/multicategory_bc_formal.yaml"))
    parser.add_argument("--env-config", default=str(
        DEXGRASP_ROOT / "cfg/shadow_hand_grasp_dexrep_ijrr.yaml"))
    parser.add_argument("--train-config", default=str(
        DEXGRASP_ROOT / "cfg/ppo1/config.yaml"))
    parser.add_argument("--output-dir", default=str(
        REPO_ROOT / "custom_tools/results/bc_closed_loop_diagnostic_aligned"))
    parser.add_argument("--seed", type=int, default=2025)
    parser.add_argument("--horizon", type=int, default=122)
    parser.add_argument("--min-free-vram-mb", type=int, default=4500)
    parser.add_argument("--sim-device", default="cuda:0")
    parser.add_argument("--rl-device", default="cuda:0")
    parser.add_argument("--show-viewer", action="store_true")
    parser.add_argument("--num-envs", type=int, default=0)
    return parser.parse_args()


def resolve_paths(cli):
    for name in ("trajectory_selection", "trajectory_root", "bc_checkpoint",
                 "bc_config", "env_config", "train_config", "output_dir"):
        value = getattr(cli, name)
        if value:
            setattr(cli, name, str(Path(value).expanduser().resolve()))


def load_selected_arrays(root, object_ids, indices_by_object):
    observations = []
    actions = []
    labels = []
    for object_id in object_ids:
        source = np.load(
            Path(root) / (object_id + ".npy"), allow_pickle=True).item()
        indices = [int(value) for value in indices_by_object[object_id]]
        observations.append(source["obs"][indices].copy())
        actions.append(source["vis_unscale_actions"][indices].copy())
        labels.extend({
            "object_id": object_id,
            "category": object_id.split("-", 2)[1],
            "source_index": source_index,
        } for source_index in indices)
    observations = np.concatenate(observations, axis=0)
    actions = np.concatenate(actions, axis=0)
    if observations.shape[:2] != actions.shape[:2]:
        raise ValueError("Expert observations and actions are not aligned")
    return observations, actions, labels


def reset_task(task, torch):
    task.random_time = False
    task.reset_buf[:] = 1
    task.progress_buf[:] = 0
    zeros = torch.zeros((task.num_envs, 28), device=task.device)
    task.step(zeros, id=-1)
    task.progress_buf[:] = 0
    task.successes[:] = 0
    return task.obs_buf.clone()


def success_update(task, peak_count, peak_mask, ever_success):
    success = task.successes > 0
    ever_success |= success
    count = int(success.sum().item())
    if count > peak_count:
        return count, success.clone(), ever_success
    return peak_count, peak_mask, ever_success


def replay_expert(task, expert_actions, horizon, torch):
    reset_task(task, torch)
    peak_count = 0
    peak_mask = torch.zeros(task.num_envs, dtype=torch.bool, device=task.device)
    ever_success = torch.zeros_like(peak_mask)
    initial_height = task.object_pos[:, 2].clone()
    maximum_lift = torch.zeros(task.num_envs, device=task.device)
    for step in range(horizon):
        frame = min(step, expert_actions.shape[1] - 1)
        task.step(expert_actions[:, frame], step + 1)
        peak_count, peak_mask, ever_success = success_update(
            task, peak_count, peak_mask, ever_success)
        maximum_lift = torch.maximum(
            maximum_lift, task.object_pos[:, 2] - initial_height)
    return {
        "official_peak_success_count": peak_count,
        "official_peak_success_rate": peak_count / task.num_envs,
        "official_peak_success_env_indices": peak_mask.nonzero(
            as_tuple=False).flatten().cpu().tolist(),
        "diagnostic_ever_success_count": int(ever_success.sum().item()),
        "diagnostic_ever_success_rate": float(ever_success.float().mean().item()),
        "mean_maximum_lift_m": float(maximum_lift.mean().item()),
    }


def teacher_forced_predictions(model, expert_obs, pro_dim, torch):
    processed = process_observation(expert_obs, pro_dim, torch)
    flat = processed.reshape(-1, processed.shape[-1])
    predictions = []
    with torch.no_grad():
        for start in range(0, flat.shape[0], 1024):
            predictions.append(model.model.act_inference(flat[start:start + 1024]))
    return processed, torch.cat(predictions, dim=0).reshape(
        processed.shape[0], processed.shape[1], 28).clamp(-1.0, 1.0)


def rollout_bc(task, model, expert_processed, expert_actions, horizon, pro_dim,
               torch):
    raw_obs = reset_task(task, torch)
    peak_count = 0
    peak_mask = torch.zeros(task.num_envs, dtype=torch.bool, device=task.device)
    ever_success = torch.zeros_like(peak_mask)
    initial_height = task.object_pos[:, 2].clone()
    maximum_lift = torch.zeros(task.num_envs, device=task.device)
    active = torch.ones(task.num_envs, dtype=torch.bool, device=task.device)
    closed_predictions = []
    prop_errors = []
    active_masks = []
    frames = expert_actions.shape[1]

    for step in range(horizon):
        live_processed = process_observation(raw_obs, pro_dim, torch)
        with torch.no_grad():
            action = model.model.act_inference(live_processed).clamp(-1.0, 1.0)
        if step < frames:
            closed_predictions.append(action.clone())
            prop_errors.append(
                live_processed[:, :pro_dim] - expert_processed[:, step, :pro_dim])
            active_masks.append(active.clone())
        task.step(action, step + 1)
        peak_count, peak_mask, ever_success = success_update(
            task, peak_count, peak_mask, ever_success)
        maximum_lift = torch.maximum(
            maximum_lift, task.object_pos[:, 2] - initial_height)
        if step < frames:
            active &= task.reset_buf <= 0
        raw_obs = task.obs_buf.clone()

    return {
        "official_peak_success_count": peak_count,
        "official_peak_success_rate": peak_count / task.num_envs,
        "official_peak_success_env_indices": peak_mask.nonzero(
            as_tuple=False).flatten().cpu().tolist(),
        "diagnostic_ever_success_count": int(ever_success.sum().item()),
        "diagnostic_ever_success_rate": float(ever_success.float().mean().item()),
        "mean_maximum_lift_m": float(maximum_lift.mean().item()),
    }, torch.stack(closed_predictions), torch.stack(prop_errors), torch.stack(active_masks)


def masked_mean(values, mask):
    expanded = mask
    while expanded.ndim < values.ndim:
        expanded = expanded.unsqueeze(-1)
    expanded = expanded.expand_as(values)
    if not expanded.any():
        return None
    return float(values[expanded].mean().item())


def summarize_range(teacher_error, closed_error, prop_error, active_mask,
                    start, stop, torch):
    result = {"frames": [start, stop - 1],
              "active_comparisons": int(active_mask[start:stop].sum().item())}
    teacher_mask = torch.ones_like(active_mask[start:stop])
    for name, left, right in ACTION_GROUPS:
        result["teacher_{}_mae".format(name)] = masked_mean(
            teacher_error[start:stop, :, left:right], teacher_mask)
        result["closed_loop_{}_mae".format(name)] = masked_mean(
            closed_error[start:stop, :, left:right], active_mask[start:stop])
    squared_prop = prop_error[start:stop].square().mean(dim=-1)
    prop_mse = masked_mean(squared_prop, active_mask[start:stop])
    result["closed_loop_prop_rmse"] = (
        prop_mse ** 0.5 if prop_mse is not None else None)
    teacher = result["teacher_all_mae"]
    closed = result["closed_loop_all_mae"]
    result["closed_to_teacher_action_error_ratio"] = (
        closed / teacher if teacher and closed is not None else None)
    return result


def save_frame_csv(path, teacher_error, closed_error, prop_error, active_mask):
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=(
            "frame", "stage", "active_trajectories", "teacher_action_mae",
            "closed_loop_action_mae", "closed_loop_prop_rmse"))
        writer.writeheader()
        for frame in range(teacher_error.shape[0]):
            stage = next(name for name, start, stop in STAGES
                         if start <= frame < stop)
            mask = active_mask[frame]
            prop_mse = masked_mean(
                prop_error[frame].square().mean(dim=-1), mask)
            writer.writerow({
                "frame": frame,
                "stage": stage,
                "active_trajectories": int(mask.sum().item()),
                "teacher_action_mae": masked_mean(
                    teacher_error[frame], np_to_torch_ones(mask)),
                "closed_loop_action_mae": masked_mean(
                    closed_error[frame], mask),
                "closed_loop_prop_rmse": (
                    prop_mse ** 0.5 if prop_mse is not None else ""),
            })


def np_to_torch_ones(reference):
    return reference.new_ones(reference.shape)


def save_plot(path, teacher_error, closed_error, prop_error, active_mask):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    frames = np.arange(teacher_error.shape[0])
    teacher_curve = teacher_error.mean(dim=(1, 2)).cpu().numpy()
    closed_curve = []
    prop_curve = []
    for frame in range(len(frames)):
        mask = active_mask[frame]
        closed_curve.append(masked_mean(closed_error[frame], mask))
        mse = masked_mean(prop_error[frame].square().mean(dim=-1), mask)
        prop_curve.append(mse ** 0.5 if mse is not None else np.nan)

    fig, axes = plt.subplots(3, 1, figsize=(8, 8), sharex=True)
    axes[0].plot(frames, teacher_curve, label="teacher-forced BC", linewidth=2)
    axes[0].plot(frames, closed_curve, label="closed-loop BC", linewidth=2)
    axes[0].set_ylabel("Action MAE")
    axes[0].legend()
    axes[1].plot(frames, prop_curve, color="tab:orange", linewidth=2)
    axes[1].set_ylabel("Proprioception RMSE")
    axes[2].plot(frames, active_mask.sum(dim=1).cpu().numpy(),
                 color="tab:green", linewidth=2)
    axes[2].set_ylabel("Active trajectories")
    axes[2].set_xlabel("Expert trajectory frame")
    for axis in axes:
        axis.grid(alpha=0.25)
        for _, start, _ in STAGES[1:]:
            axis.axvline(start, color="gray", linestyle="--", alpha=0.5)
    fig.suptitle("BC error accumulation on 32 selected expert trajectories")
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def run(cli):
    if cli.horizon < 69:
        raise ValueError("--horizon must cover all 69 valid expert actions")
    resolve_paths(cli)
    with open(cli.trajectory_selection, "r", encoding="utf-8") as handle:
        selection = yaml.safe_load(handle)
    if selection.get("status") != "frozen_stage1_selection":
        raise ValueError("Trajectory selection is not frozen")
    trajectory_root = cli.trajectory_root or selection["trajectory_root"]
    trajectory_root = str(Path(trajectory_root).expanduser().resolve())
    object_ids = selection["object_ids"]
    indices_by_object = selection["trajectory_indices_by_object"]
    expert_obs_np, expert_actions_np, labels = load_selected_arrays(
        trajectory_root, object_ids, indices_by_object)
    raw_trajectory_frames = expert_obs_np.shape[1]
    if raw_trajectory_frames != 70:
        raise ValueError("This diagnostic expects 70-frame BC trajectories")
    # Preprocessing stores action i-1 after stepping source action i.  The
    # 70th action slot is never assigned and remains an all-zero placeholder;
    # the official Dataset remaps that final flat index for the same reason.
    expert_obs_np = expert_obs_np[:, :-1]
    expert_actions_np = expert_actions_np[:, :-1]

    output_dir = Path(cli.output_dir)
    if output_dir.exists() and any(output_dir.iterdir()):
        raise FileExistsError(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    evaluation_support.initialize_cuda_runtime()
    evaluation_support.require_free_vram(cli.min_free_vram_mb)
    evaluation_support.initialize_runtime()
    import torch

    task = None
    original_cwd = Path.cwd()
    try:
        os.chdir(str(DEXGRASP_ROOT))
        cli.num_envs = len(labels)
        official_args = evaluation_support.build_official_args(cli)
        base_cfg, cfg_train, _ = evaluation_support.load_cfg(official_args)
        evaluation_support.set_seed(
            cli.seed, cfg_train.get("torch_deterministic", False))
        model, model_name, checkpoint_path, _ = evaluation_support.load_model(cli)
        if model_name != "ActorCriticDexRep":
            raise ValueError("This diagnostic currently supports ActorCriticDexRep")
        trajectory_data = indexed_trajectory_data(
            trajectory_root, object_ids, indices_by_object)
        config = {"seed": cli.seed}
        task = build_task(
            cli, config, official_args, base_cfg, cfg_train, trajectory_data)
        if task.num_envs != len(labels):
            raise RuntimeError("Simulator trajectory order does not match selection")

        expert_obs = torch.as_tensor(
            expert_obs_np, device=cli.rl_device, dtype=torch.float32)
        expert_actions = torch.as_tensor(
            expert_actions_np, device=cli.rl_device, dtype=torch.float32)
        model.eval()
        pro_dim = int(task.cfg["env"]["obs_dim"]["prop"])
        expert_processed, teacher_predictions = teacher_forced_predictions(
            model, expert_obs, pro_dim, torch)
        expert_result = replay_expert(task, expert_actions, cli.horizon, torch)
        bc_result, closed_predictions, prop_error, active_mask = rollout_bc(
            task, model, expert_processed, expert_actions, cli.horizon,
            pro_dim, torch)

        teacher_error = (teacher_predictions - expert_actions).abs().transpose(0, 1)
        closed_error = (
            closed_predictions - expert_actions.transpose(0, 1)).abs()
        overall = summarize_range(
            teacher_error, closed_error, prop_error, active_mask,
            0, expert_actions.shape[1], torch)
        stages = {
            name: summarize_range(
                teacher_error, closed_error, prop_error, active_mask,
                start, stop, torch)
            for name, start, stop in STAGES
        }
        result = {
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "diagnostic": "BC teacher forcing versus closed loop",
            "official_code_modified": False,
            "official_success_definition_changed": False,
            "bc_checkpoint": str(checkpoint_path),
            "trajectory_selection": cli.trajectory_selection,
            "trajectory_root": trajectory_root,
            "seed": cli.seed,
            "trajectory_count": len(labels),
            "raw_trajectory_frames": raw_trajectory_frames,
            "valid_aligned_frames": int(expert_actions.shape[1]),
            "discarded_final_zero_action_placeholder": True,
            "rollout_horizon": cli.horizon,
            "stage_definition": {
                name: [start, stop - 1] for name, start, stop in STAGES},
            "expert_action_replay": expert_result,
            "bc_closed_loop_rollout": bc_result,
            "overall_error": overall,
            "stage_errors": stages,
            "trajectories": labels,
            "interpretation_rule": {
                "large_teacher_error": "BC did not fit expert state-action pairs",
                "closed_much_larger_than_teacher": "closed-loop distribution shift and error accumulation",
                "expert_replay_failure": "data/simulator reproduction mismatch",
            },
        }
        yaml_path = output_dir / "summary.yaml"
        with yaml_path.open("w", encoding="utf-8") as handle:
            yaml.safe_dump(result, handle, allow_unicode=True, sort_keys=False)
        save_frame_csv(
            output_dir / "frame_metrics.csv", teacher_error, closed_error,
            prop_error, active_mask)
        save_plot(
            output_dir / "error_curves.png", teacher_error, closed_error,
            prop_error, active_mask)
        print("Expert replay official peak: {}/{}".format(
            expert_result["official_peak_success_count"], len(labels)))
        print("BC closed-loop official peak: {}/{}".format(
            bc_result["official_peak_success_count"], len(labels)))
        print("Teacher-forced action MAE: {:.6f}".format(
            overall["teacher_all_mae"]))
        print("Closed-loop action MAE: {:.6f}".format(
            overall["closed_loop_all_mae"]))
        print("Closed/teacher error ratio: {:.3f}".format(
            overall["closed_to_teacher_action_error_ratio"]))
        print("Saved diagnostic: {}".format(yaml_path))
        return yaml_path
    finally:
        if task is not None:
            task.clean_sim()
        os.chdir(str(original_cwd))
        gc.collect()
        if "torch" in locals():
            torch.cuda.empty_cache()


if __name__ == "__main__":
    run(parse_cli())
